name: Build and Deploy
on:
  push:
    branches: [main]
    
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TARGET_REPO: trainlink-org/trainlink-org.github.io
        TARGET_BRANCH: main
        BUILD_SCRIPT: npm i && npm run build
        BUILD_DIR: docs/.vuepress/dist
        CNAME: https://www.trainlink-org.github.io
